### ISSUE TITLE
Reunião QUARTA

### ISSUE THREAD

**Issue by LoriaLawrenceZ** [OZimbres/FIAP-Fase1#8]
<h1 algin=center>Reunião Quarta</h1>
<h2>Informações</h2>
<ul>
    <li>Google Meet (<a href="https://meet.google.com/xhm-miwa-mez">link da reunião</a>)</li>
    <li>28/02/2024 | 20:00</li>
</ul>
<h2>Assuntos</h2>
<ul>
    <li>Organização Geral</li>
    <li>Primeira divisão de grupos</li>
</ul>

**Comment by LoriaLawrenceZ** [comment]
@OZimbres/fiap , quaisquer adições/alterações, comentem aqui (ou na aba de issue, que eu altero a descrição dela)

**Comment by HenriqueSaniW** [comment]
Será que é muito ruim começar a reunião as 19:00 ou 19:30, pois as 20:00 de quarta é o único horário da semana que fica um pouco complicado para mim kkk
